# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install openjdk-8-jdk-headless
    cd ..
    git clone https://github.com/rinsuki/ForgeBuilder
    cd ForgeBuilder
    mvn package -q
  displayName: 'Initialize ForgeBuilder'
- script: |
    java -jar ../ForgeBuilder/target/ForgeBuilder-*.jar .
  displayName: 'Build QuarryPlus'
- publish: 'target/*/*.jar'